services:
  db:
    image: postgres:16
    container_name: goyos_secrets_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: goyos_secrets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/goyos_secrets_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: