"""empty message

Revision ID: 5653041e82d9
Revises: 7d9674972c2b
Create Date: 2025-07-07 22:39:45.400259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5653041e82d9'
down_revision: Union[str, None] = '7d9674972c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('restaurant_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'menu_items', 'restaurantdbmodel', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'pre_order_items', 'reservationdbmodel', ['reservation_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_order_items', type_='foreignkey')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.drop_column('menu_items', 'restaurant_id')
    # ### end Alembic commands ###
